// <auto-generated />
using System;
using Hirebase.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hirebase.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422125949_PendingChanges")]
    partial class PendingChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GitHubProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FetchStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Followers")
                        .HasColumnType("integer");

                    b.Property<string>("GitHubId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GitHubUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProfileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PublicRepos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId")
                        .IsUnique();

                    b.ToTable("GitHubProfiles");
                });

            modelBuilder.Entity("Hirebase.Domain.Entities.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Hirebase.Domain.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Hirebase.Domain.Entities.CandidateProfiles.CandidatePreferredRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("PreferredRoles");
                });

            modelBuilder.Entity("Hirebase.Domain.Entities.CandidateProfiles.CandidateProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("AvailableFrom")
                        .HasColumnType("date");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CvUrl")
                        .HasColumnType("text");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PersonalSiteUrl")
                        .HasColumnType("text");

                    b.Property<int?>("RemotePreference")
                        .HasColumnType("integer");

                    b.Property<int?>("SalaryMax")
                        .HasColumnType("integer");

                    b.Property<int?>("SalaryMin")
                        .HasColumnType("integer");

                    b.Property<int?>("SeniorityLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CandidateProfiles");
                });

            modelBuilder.Entity("Hirebase.Domain.Entities.CandidateProfiles.SoftSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Skill")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidateProfileId");

                    b.ToTable("SoftSkills");
                });

            modelBuilder.Entity("GitHubProfile", b =>
                {
                    b.HasOne("Hirebase.Domain.Entities.CandidateProfiles.CandidateProfile", "CandidateProfile")
                        .WithOne("GitHubProfile")
                        .HasForeignKey("GitHubProfile", "CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("Hirebase.Domain.Entities.Auth.RefreshToken", b =>
                {
                    b.HasOne("Hirebase.Domain.Entities.Auth.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hirebase.Domain.Entities.CandidateProfiles.CandidatePreferredRole", b =>
                {
                    b.HasOne("Hirebase.Domain.Entities.CandidateProfiles.CandidateProfile", "CandidateProfile")
                        .WithMany("PreferredRoles")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("Hirebase.Domain.Entities.CandidateProfiles.CandidateProfile", b =>
                {
                    b.HasOne("Hirebase.Domain.Entities.Auth.User", "User")
                        .WithOne()
                        .HasForeignKey("Hirebase.Domain.Entities.CandidateProfiles.CandidateProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hirebase.Domain.Entities.CandidateProfiles.SoftSkill", b =>
                {
                    b.HasOne("Hirebase.Domain.Entities.CandidateProfiles.CandidateProfile", "CandidateProfile")
                        .WithMany("SoftSkills")
                        .HasForeignKey("CandidateProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateProfile");
                });

            modelBuilder.Entity("Hirebase.Domain.Entities.Auth.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Hirebase.Domain.Entities.CandidateProfiles.CandidateProfile", b =>
                {
                    b.Navigation("GitHubProfile");

                    b.Navigation("PreferredRoles");

                    b.Navigation("SoftSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
